/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_azsy_zstokhttp_jnitest_JniUtils */

#ifndef _Included_cn_azsy_zstokhttp_jnitest_JniUtils
#define _Included_cn_azsy_zstokhttp_jnitest_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_azsy_zstokhttp_jnitest_JniUtils
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_azsy_zstokhttp_jnitest_JniUtils_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
